name: Patch IPA

permissions:
  contents: write

on:
  workflow_dispatch:
    inputs:
      ipa_url:
        required: true
        description: Direct atau Google Drive link

jobs:
  build:
    runs-on: macos-latest
    env:
      IPA_LINK_INPUT: ${{ github.event.inputs.ipa_url }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Download ipapatch
        run: |
          curl -L https://github.com/asdfzxcvbn/ipapatch/releases/download/v1.1.2/ipapatch.macos-arm64 -o ipapatch
          chmod +x ipapatch

      - name: Download IPA
        run: |
          mkdir -p package
          TARGET=package/input.ipa
          if [[ "$IPA_LINK_INPUT" == *"drive.google.com"* ]]; then
            python3 tools/converter.py "$IPA_LINK_INPUT" -o "$TARGET"
          else
            curl -L -o "$TARGET" "$IPA_LINK_INPUT"
          fi
          [ -s "$TARGET" ] || (echo "::error::Download gagal"; exit 1)

      - name: Patch IPA dan Rename
        run: |
          # Menjalankan main.py untuk patch IPA
          python3 main.py
          # Ekstrak Info.plist dari Payload/*.app/Info.plist
          unzip -p package/patched.ipa "Payload/*/Info.plist" > temp.plist || (echo "::error::Gagal ekstrak Info.plist"; exit 1)
          # Debug: Tampilkan isi Info.plist
          echo "Isi Info.plist:"
          cat temp.plist
          # Ambil CFBundleDisplayName dan CFBundleShortVersionString
          DISPLAY_NAME=$(PlistBuddy -c "Print CFBundleDisplayName" temp.plist 2>/dev/null || echo "input")
          VERSION=$(PlistBuddy -c "Print CFBundleShortVersionString" temp.plist 2>/dev/null || echo "0.0")
          echo "CFBundleDisplayName: $DISPLAY_NAME"
          echo "CFBundleShortVersionString: $VERSION"
          # Sanitasi DISPLAY_NAME untuk menghindari karakter tidak valid
          DISPLAY_NAME=$(echo "$DISPLAY_NAME" | tr -d '[:space:]/\\')
          # Rename file IPA menjadi {CFBundleDisplayName}_v{CFBundleShortVersionString}.ipa
          NEW_IPA_NAME="${DISPLAY_NAME}_v${VERSION}.ipa"
          mv package/patched.ipa "package/${NEW_IPA_NAME}"
          # Simpan path IPA yang sudah diganti nama ke GITHUB_ENV
          echo "final_ipa_path=package/${NEW_IPA_NAME}" >> $GITHUB_ENV
          # Hapus file sementara
          rm temp.plist

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: release-${{ github.run_id }}
          name: Release ${{ github.run_id }}
          files: ${{ env.final_ipa_path }}
          draft: false
          prerelease: false