name: Patch IPA

permissions:
  contents: write

on:
  workflow_dispatch:
    inputs:
      ipa_url:
        required: true
        description: Direct atau Google Drive link

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      IPA_LINK_INPUT: ${{ github.event.inputs.ipa_url }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Download ipapatch
        run: |
          curl -L https://github.com/asdfzxcvbn/ipapatch/releases/latest/download/ipapatch.linux-amd64 -o ipapatch
          chmod +x ipapatch

      - name: Download IPA
        run: |
          mkdir -p package
          TARGET=package/input.ipa
          if [[ "$IPA_LINK_INPUT" == *"drive.google.com"* ]]; then
            python3 tools/converter.py "$IPA_LINK_INPUT" -o "$TARGET"
          else
            wget -q -O "$TARGET" "$IPA_LINK_INPUT"
          fi
          [ -s "$TARGET" ] || (echo "::error::Download gagal"; exit 1)

      - name: Extract Original Metadata
        run: |
          unzip -p package/input.ipa "Payload/*/Info.plist" > temp.plist
          python3 -c "import plistlib, os; plist = plistlib.load(open('temp.plist', 'rb')); display_name = plist.get('CFBundleDisplayName', 'input'); version = plist.get('CFBundleShortVersionString', '0.0'); print(f'ORIGINAL_DISPLAY_NAME={display_name}'); print(f'ORIGINAL_VERSION={version}')" >> $GITHUB_ENV
          rm temp.plist

      - name: Patch IPA
        run: python3 main.py

      - name: Check Patched IPA Metadata
        run: |
          unzip -p package/patched.ipa "Payload/*/Info.plist" > temp.plist
          cat temp.plist
          rm temp.plist

      - name: Rename Output IPA
        id: rename
        run: |
          # Menjalankan rename.py dan menetapkan output IPA yang sudah di-rename
          RENAMED_IPA_PATH=$(python3 tools/rename.py)
      
          # Menulis output path IPA yang sudah di-rename
          echo "final_ipa_path=$RENAMED_IPA_PATH" >> $GITHUB_ENV
          echo "Renamed IPA path: $RENAMED_IPA_PATH"

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: release-${{ github.run_id }}
          name: Release ${{ github.run_id }}
          files: ${{ env.final_ipa_path }}
          draft: false
          prerelease: false