name: Patch IPA

on:
  workflow_dispatch:
    inputs:
      ipa_url:
        description: 'Direct download / Google Drive link'
        required: true

jobs:
  patch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install Python dependencies
        run: pip install --upgrade pip

      - name: Setup folder
        run: mkdir -p package

      - name: Convert Google Drive link if needed
        run: |
          URL="${{ github.event.inputs.ipa_url }}"
          if [[ "$URL" == *"drive.google.com"* ]]; then
            URL=$(python3 tools/converter.py "$URL")
          fi
          echo "$URL" > url.txt
        shell: bash

      - name: Download IPA
        run: |
          curl -L "$(cat url.txt)" -o package/input.ipa

      - name: Download ipapatch binary
        run: |
          curl -L https://github.com/asdfzxcvbn/ipapatch/releases/download/v1.1.2/ipapatch.linux-amd64 -o ipapatch
          chmod +x ipapatch
          sudo mv ipapatch /usr/local/bin/ipapatch

      - name: Run patch script
        run: python3 main.py

      - name: Get output filename
        id: ipaout
        run: |
          FILE=$(ls package/*.ipa | grep -v input.ipa)
          echo "ipa_file=$FILE" >> $GITHUB_OUTPUT

      - name: Create or update release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: release-$(date +'%Y-%m-%d')
          name: Release $(date +'%Y-%m-%d')
          files: ${{ steps.ipaout.outputs.ipa_file }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}