name: Patch IPA

permissions:
  contents: write

on:
  workflow_dispatch:
    inputs:
      ipa_url:
        required: true
        description: Direct atau Google Drive link

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      IPA_LINK_INPUT: ${{ github.event.inputs.ipa_url }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install dependencies
        run: pip install -r requirements.txt || true

      - name: Download IPA
        run: |
          mkdir -p package
          TARGET=package/input.ipa
          if [[ "$IPA_LINK_INPUT" == *"drive.google.com"* ]]; then
            python3 tools/converter.py "$IPA_LINK_INPUT" -o "$TARGET"
          else
            wget -q -O "$TARGET" "$IPA_LINK_INPUT"
          fi
          [ -s "$TARGET" ] || (echo "::error::Download gagal"; exit 1)

      - name: Patch IPA
        run: python3 main.py

      - name: Rename Output IPA
        id: rename
        run: python3 tools/rename.py

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: release-${{ github.run_id }}
          name: Release ${{ github.run_id }}
          files: ${{ steps.rename.outputs.final_ipa_path }}
          draft: false
          prerelease: false